### ISSUE TITLE
[Feature] Use dependabot version updates to keep devcontainers up-to-date

### ISSUE THREAD

**Issue by sinsukehlab** [skills/copilot-codespaces-vscode#123]
### Summary

Dependabot Version Updates Support devcontainers

### Changes

Add an update to dependabot.yml

```yml
  - package-ecosystem: "devcontainers" # See documentation for possible values
    directory: "/"
    schedule:
      interval: monthly
```

### Additional context

https://github.blog/changelog/2024-01-24-dependabot-version-updates-support-devcontainers/
https://containers.dev/guide/dependabot
