### ISSUE TITLE
[Feature] workflow verification can be smarter

### ISSUE THREAD

**Issue by luwangshell** [skills/copilot-codespaces-vscode#187]
### Summary

Learners need to use the exact same word (including upper/lower case) as the prompt, following the instruction. For example, if the instruction says "Create web server", learners need to type "Create web server" instead of "**c**reate web server". Otherwise, the workflow will fail because it looks up the exact word in the source file.

### Changes

Suggest to either making the verification smarter or stating clearly / expectation to the learners in the Readme.

### Additional context

Example:
```
# Verify the learner added the file contents.
      - name: Check workflow contents, jobs
        uses: skills/action-check-file@v1
        with:
          file: "comments.js"
          search: "Create web server"
```
